export const FETCH_QUIZ_START = "quiz/FETCH_QUIZ_START";
export const FETCH_QUIZ_SUCCESS = "quiz/FETCH_QUIZ_SUCCESS";
export const FETCH_QUIZ_BY_ID_SUCCESS = "quiz/FETCH_QUIZ_BY_ID_SUCCESS";
export const FETCH_QUIZ_ERROR = "quiz/SET_QUIZ_ERROR";


